apiVersion: apps/v1
kind: Deployment
metadata:
  name: maid-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maid-service
  template:
    metadata:
      labels:
        app: maid-service
    spec:
      containers:
        - name: maid-service
          image: gcr.io/maid-service-465009/maid-service
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: uri
